DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  hashedPassword VARCHAR(64) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS favorite;

CREATE TABLE favorite (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL, 
    isbn VARCHAR(13) NOT NULL, 
    UNIQUE(user_id, isbn)
);